name: contributed_machinery
description: Fast Request/Answer app

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0+1
  uuid: ^2.2.0
  flutter_bloc: ^6.0.1
  auto_route: ^0.6.7
  get_it: ^4.0.4
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0
  cloud_firestore: ^0.14.0
  firebase_analytics: ^6.0.0
  injectable: ^1.0.4
  flushbar: ^1.10.4
  json_annotation: ^3.0.1
  styled_widget: ^0.2.1+2
  time: ^1.3.0
  rxdart: ^0.24.1
  provider: ^4.3.2
  flutter_slidable: ^0.5.5
  flutter_markdown: ^0.4.3
  bubble: ^1.1.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  build_runner:
  freezed: ^0.11.5
  auto_route_generator: ^0.6.8
  injectable_generator: ^1.0.4
  json_serializable: ^3.4.0

flutter:
  uses-material-design: true
