name: contributed_machinery
description: Fast Request/Answer app

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0
  uuid: ^2.2.0
  flutter_bloc: ^5.0.0
  auto_route: ^0.6.0+1
  get_it: ^4.0.2
  meta: ^1.1.8
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_analytics: ^5.0.16
  injectable: ^0.4.0+1
  flushbar: ^1.10.4
  json_annotation: ^3.0.1
  styled_widget: ^0.2.1+2
  flutter_hooks: ^0.10.0
  time: ^1.3.0
  kt_dart: ^0.7.0+1
  rxdart: ^0.24.1
  reorderables: ^0.3.2
  provider: ^4.1.3
  implicitly_animated_reorderable_list: ^0.2.3
  flutter_slidable: ^0.5.4
  flutter_markdown: ^0.4.2
  bubble: ^1.1.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  build_runner:
  freezed: ^0.11.2
  auto_route_generator: ^0.6.0
  injectable_generator: ^0.4.1
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
